name: Documentation

on:
  push:
    branches:
      - docs
    paths:
      - 'docsite/**'
      - 'docs_zh/**'
      - '.github/workflows/docs.yml'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v6
      - name: Fetch Source
        run: |
          git clone https://github.com/RooCodeInc/Roo-Code-Docs.git docsite
      - name: Build Docs
        run: |
          cp -r docs_zh/* docsite/docs/
          cd docsite/
          npm install
          npm build
      - name: Copy CNAME  
        run: cp CNAME docsite/build/

      ### SSH Server WEB
      - name: Set up SSH
        uses: LuisEnMarroquin/setup-ssh-action@v3.0.0
        with:
          ORIGIN: ${{ secrets.SSH_HOSTNAME }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: webserver
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USERNAME }}
      - run: echo "" >> ~/.ssh/access  # fix
      - name: Deploy the website
        env: 
          WEBROOT: /data/wwwroot/roocode
        run: |
          ssh webserver "rm -rf $WEBROOT && mkdir -p $WEBROOT"
          scp -r docsite/build/* webserver:${WEBROOT}

      ### GitHub Pages
      # - run: cp CNAME docsite/build/
      # - uses: actions/upload-pages-artifact@v4
      #   with:
      #     path: docsite/build
      # - uses: actions/deploy-pages@v4
      #   id: deployment

      - name: Deploy to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsite/build
