name: Documentation

on:
  push:
    branches:
      - docs
    paths:
      - 'docs_zh/**'
      - '.github/workflows/docs.yml'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/configure-pages@v5
      - uses: actions/checkout@v6
      - name: Fetch Source
        run: |
          git clone https://github.com/RooCodeInc/Roo-Code-Docs.git docsite
          cd docsite
          git checkout $(cat ../commit.txt)
      - name: Build Docs
        run: |
          cp -r docs_zh/* docsite/docs/
          cd docsite/
          npm install
          npm run build
      - name: Copy CNAME  
        run: cp CNAME docsite/build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: docs-site
          path: docsite/build
          retention-days: 1

  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/configure-pages@v5
      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: docs-site
          path: ./build
      - name: Deploy to Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      # - uses: actions/upload-pages-artifact@v4
      #   with:
      #     path: docsite/build
      # - uses: actions/deploy-pages@v4
      #   id: deployment

  deploy-ssh-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: docs-site
          path: ./build
      - name: Compress to tar.xz
        run: |
          tar -cJf docs-site.tar.xz build/
      - name: Set up SSH
        uses: LuisEnMarroquin/setup-ssh-action@v3.0.0
        with:
          ORIGIN: ${{ secrets.SSH_HOSTNAME }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: webserver
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USERNAME }}
      - run: echo "" >> ~/.ssh/access  # fix
      - name: Deploy the website
        env:
          WEBROOT: /data/wwwroot/roocode
        run: |
          ssh webserver "rm -rf $WEBROOT && mkdir -p $WEBROOT"
          scp docs-site.tar.xz webserver:${WEBROOT}/
          ssh webserver "cd $WEBROOT && tar -xJf docs-site.tar.xz --strip-components=1 && rm -f docs-site.tar.xz"
